SELECT
    A.ATTR_ID,
    A.ATTR_NM,
    S.SCR_GRP_TYPE,
    S.WEIGHTAGE,
    V.MIN_VALUE,
    V.MAX_VALUE,
    V.ATTR_SCORE
FROM
[TS_STAR].[dbo].[TS_ALERT_SCR_ATTR] A
LEFT JOIN
[TS_STAR].[dbo].[TS_ALERT_SCR_ATTR_VAL] V ON A.ATTR_ID = V.SCR_ATTR_ID
LEFT JOIN
[TS_STAR].[dbo].[TS_ALERT_SCR_GRP] S ON A.SCR_GRP_ID = S.SCR_GRP_ID
