SELECT
    TS_ALERT.ALERT_ID,
    TS_ALERT.ALERT_TX,
    TS_ALERT.PREV_MATCH_CT_ALL,
    TS_ALERT.PREV_MATCH_CT,
    TS_ALERT.SCENARIO_ID,
    UPPER(TS_STATUS.STATUS) AS STATUS_CD,
    --TS_ALERT_CUST
    TS_ALERT_CUST.CUST_ID,
    TS_ALERT_CUST.ACCT_ID,

    TS_ALERT_INVGTN.AUTO_REASN_FL,
    TS_ALERT_CASE.ALERT_INVSTN_ID,
    TS_SAR_CASE.CASE_ID,
    TS_SAR.SAR_ID
FROM
    TS_ALERT
LEFT JOIN
    TS_ALERT_CUST ON TS_ALERT.ALERT_ID = TS_ALERT_CUST.ALERT_ID
LEFT JOIN
    TS_ALERT_INVGTN ON TS_ALERT_INVGTN.ALERT_ID = TS_ALERT.ALERT_ID
LEFT JOIN
    TS_ALERT_CASE ON TS_ALERT_INVGTN.ALERT_INVSTN_ID = TS_ALERT_CASE.ALERT_INVSTN_ID
--JOIN
    --TS_CASE ON TS_ALERT_CASE.CASE_ID = TS_CASE.CASE_ID
LEFT JOIN
    TS_SAR_CASE ON TS_ALERT_CASE.CASE_ID = TS_SAR_CASE.CASE_ID
LEFT JOIN
    TS_SAR ON TS_SAR_CASE.SAR_ID = TS_SAR.SAR_ID
LEFT JOIN
    TS_STATUS ON TS_STATUS.STATUS_ID = TS_ALERT_INVGTN.STATUS_ID